/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-secondary-container": "#fefcff",
        "primary-fixed-dim": "#b0c8eb",
        "on-error": "#ffffff",
        "tertiary": "#1a0b00",
        "surface-variant": "#e2e2e7",
        "primary-fixed": "#d2e4ff",
        "inverse-surface": "#2e3034",
        "on-tertiary-container": "#ae835a",
        "tertiary-fixed-dim": "#eebd90",
        "surface-tint": "#49607e",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#768dad",
        "background": "#f9f9fe",
        "secondary": "#0058bc",
        "on-surface": "#1a1c1f",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#43474d",
        "surface-container-low": "#f3f3f8",
        "secondary-fixed-dim": "#adc6ff",
        "secondary-fixed": "#d8e2ff",
        "surface-container-high": "#e8e8ed",
        "on-tertiary-fixed-variant": "#613f1c",
        "surface-container-highest": "#e2e2e7",
        "on-primary-fixed-variant": "#314865",
        "surface": "#f9f9fe",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#004493",
        "primary": "#000f22",
        "tertiary-fixed": "#ffdcbe",
        "inverse-on-surface": "#f0f0f5",
        "primary-container": "#0a2540",
        "outline-variant": "#c4c6ce",
        "on-primary-fixed": "#001c37",
        "on-primary": "#ffffff",
        "surface-dim": "#d9dade",
        "on-secondary-fixed": "#001a41",
        "on-background": "#1a1c1f",
        "tertiary-container": "#381d00",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f9f9fe",
        "secondary-container": "#0070eb",
        "on-tertiary-fixed": "#2d1600",
        "outline": "#74777e",
        "inverse-primary": "#b0c8eb",
        "surface-container": "#ededf2"
      },
      fontFamily: {
        "headline": ["Manrope", "Pretendard", "sans-serif"],
        "body": ["Plus Jakarta Sans", "Pretendard", "sans-serif"],
        "label": ["Plus Jakarta Sans", "Pretendard", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
